set.seed(42)
x <- rnorm(22)
xx <- cbind( rep(1,22), x)
y <- 2 + x + rnorm(22)
coefficients(lm(y ~ x +1 ) )
solve (crossprod(xx),   crossprod(xx, y) )
qr.solve (crossprod(xx),   crossprod(xx, y) )
qr.solve(xx, y )
qr.solve(y,xx)
